{
 "title": "Go Runtime",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,10m,30m,1h,6h,12h,1d,7d" }
  ]
 },
 "panels": [
  {
   "title": "Go Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "go_info{job=\"demo-go\"}"
    }
   ]
  },
  {
   "title": "Number of GCs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=\"demo-go\"}[$interval])",
     "legendFormat": "per second - max"
    },
    {
     "expr": "increase(go_gc_duration_seconds_count{job=\"demo-go\"}[$interval])",
     "legendFormat": "total  - max"
    }
   ]
  },
  {
   "title": "GC duration average and percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{job=\"demo-go\"} / go_gc_duration_seconds_count{job=\"demo-go\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"demo-go\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"demo-go\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Go Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"demo-go\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}